comment: off

flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
        removed_code_behavior: adjust_base
      - type: patch
        informational: true
        target: auto
        removed_code_behavior: adjust_base
