name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        working-directory: java-components
        run: mvn -V -B verify -Dvalidate-format -Pcode-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: java-components/report-aggregator/target/site/jacoco-aggregate
          fail_ci_if_error: true
